#!/bin/bash -eu
#
# Copyright 2020 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# This script assumes that mongodb has already been installed and that
# a bare-bones service is running on each of the members of the cluster.
#
# The script will:
#   * Set up custom logger:
#     * Add configuration for stackdriver logging

systemctl is-active --quiet google-fluentd

# Check if google-fluentd is available
status=$?
if [ $status -eq 1 ]; then
  echo "Google-fluentd service is not running. Skip."
  rm /etc/mongodb.logger.conf
  exit 0
fi

# Overwrite mongodb.conf of fluentd-catch-all-config
mv /etc/mongodb.logger.conf /etc/google-fluentd/config.d/mongodb.conf

service google-fluentd restart
